version: '3.7'

services:
  php:
    container_name: task-api-php
    build:
      context: ./
      dockerfile: ./deployment/docker/fpm/Dockerfile
      target: fpm-dev
    platform: linux/amd64
    env_file:
      - .env
    volumes:
      - .:/var/www/:cached
      - php-fpm:/var/run
    working_dir: /var/www/
    networks:
      - task-api
    depends_on:
      - composer

  nginx:
    build:
      context: ./
      dockerfile: ./deployment/docker/nginx/Dockerfile
      args:
        FPM_HOST: task-api-php
    volumes:
      - .:/var/www/:cached
    ports:
      - "8888:80"
    networks:
      - task-api
    depends_on:
      - php


  composer:
    restart: 'no'
    image: composer:latest
    command: install --ignore-platform-reqs
    volumes:
      - .:/app

  database:
      image: mysql:5.7
      container_name: task-api-db
      restart: unless-stopped
      tty: true
      ports:
          - "3306:3306"
      environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_PASSWORD: ${DB_PASSWORD}
      volumes:
          - db:/var/lib/mysql
      networks:
          - task-api
      env_file:
          - .env

volumes:
  php-fpm:
  db:
    driver: local

networks:
  task-api:
    driver: bridge
